language: node_js

script:
  - "./gradlew check"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - client/.gradle/
    - client/node_modules/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
