sudo: required

services:
  - docker

dist: trusty
jdk: oraclejdk8
language: java

env:
  - TERM=dumb
before_install:
  - sudo apt-get install -y font-manager
  - wget https://github.com/EbenSorkin/Merriweather/releases/download/1.584/Merriweather-1.584.zip
  - unzip Merriweather-1.584.zip
  - sudo font-manager install TTF
install:
  - "./gradlew :client:npmInstall"
script:
  - "./gradlew check"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
cache:
  directories:
    - client/.gradle/
    - client/node_modules/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
